# Generated by Django 2.2.3 on 2019-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_de_criacao',
            field=models.DateField(auto_now=True),
        ),
    ]
