# Generated by Django 2.2.3 on 2019-07-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20190726_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='unknow', max_length=255),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=255)),
                ('saldo', models.FloatField(default=0.0)),
                ('agencia', models.CharField(max_length=255)),
                ('nome_banco', models.CharField(default='mybank', max_length=255, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Pessoa')),
            ],
        ),
    ]
